apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: mern-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGIubWVybi1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvYm9vay1zdG9yZT9hdXRoU291cmNlPWFkbWlu


