name: backend-api-stack
services:
  backend-service:
    image: bouthainabakouch/backend-api
    depends_on:
      - database
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-api-container
    environment:
      MONGO_URI: mongodb://root:example@database:27017/book-store?authSource=admin
      PORT: 3002
    ports:
      - "3007:3002"

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    depends_on:
      - database
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false
