# name: CI/CD Pipeline

# on:
#   push:
#     branches: 
#       - main

# env:
#   BACKEND_IMAGE: bouthainabakouch/backend-api-k8s
#   FRONTEND_IMAGE: bouthainabakouch/frontend-app-k8s
#   BUILD_NUMBER: ${{ github.run_number }}

# jobs:

#   test-backend:
#     runs-on: ubuntu-latest  
#     defaults:
#       run:
#         working-directory: backend_api
#     steps:
#       - name: Checkout backend code
#         uses: actions/checkout@v4
#       - name: Install backend dependencies
#         run: npm install
#       - name: Run backend unit tests
#         run: npm test

#   test-frontend:
#     runs-on: ubuntu-latest  
#     defaults:
#       run:
#         working-directory: frontend-app
#     steps:
#       - name: Checkout frontend code
#         uses: actions/checkout@v4
#       - name: Install frontend dependencies
#         run: npm install
#       - name: Run frontend unit tests
#         run: npm run test
#       - name: Run frontend lint
#         run: npm run lint

#   build-and-push:
#     runs-on: ubuntu-latest
#     needs: [test-backend, test-frontend]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Build backend image
#         run: docker build -t ${{ env.BACKEND_IMAGE }}:${{ env.BUILD_NUMBER }} ./backend_api

#       - name: Build frontend image
#         run: |
#           docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.BUILD_NUMBER }} \
#             --build-arg VITE_API_URL=http://api.mern.local.com:31145 ./frontend-app

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Tag and push backend image
#         run: |
#           docker tag ${{ env.BACKEND_IMAGE }}:${{ env.BUILD_NUMBER }} ${{ env.BACKEND_IMAGE }}:latest
#           docker push ${{ env.BACKEND_IMAGE }}:${{ env.BUILD_NUMBER }}
#           docker push ${{ env.BACKEND_IMAGE }}:latest

#       - name: Tag and push frontend image
#         run: |
#           docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.BUILD_NUMBER }} ${{ env.FRONTEND_IMAGE }}:latest
#           docker push ${{ env.FRONTEND_IMAGE }}:${{ env.BUILD_NUMBER }}
#           docker push ${{ env.FRONTEND_IMAGE }}:latest

